project:
  type: default
  output-dir: _site

execute:
  echo: false
  warning: false
  message: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    df-print: paged
    embed-resources: true
